apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-frontend
  namespace: argocd
spec:
  project: default
  source:
    path: Frontend/task-management/deployment
    repoURL: >-
      https://github.com/SherifEmad20/Simple-todo-app-devops-cycle.git
    targetRevision: HEAD
  destination:
    namespace: todo-app
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
